import { useThemedStyles } from "@/src/theme/useTheme";
import { useBottomTabBarHeight } from "@/src/hooks/useTabBarHeight";

export function useAlertDetailStyles() {
  const tabBarHeight = useBottomTabBarHeight();

  const styles = useThemedStyles((c) => ({
    container: { flex: 1, backgroundColor: c.bg },
    safeArea: { flex: 1 },
    centered: { alignItems: "center", justifyContent: "center", gap: 16 },
    scroll: { flex: 1 },
    scrollContent: { paddingHorizontal: 20 },
    spacer: { height: 140 + tabBarHeight }, // ← Intégré
    actionsBlock: {
      flexDirection: "row",
      gap: 10,
      paddingHorizontal: 20,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: c.cardBorder,
      paddingBottom: 16 + tabBarHeight,
      backgroundColor: c.bg,
    }, // ← Intégré
    vitalHalo: {
      position: "absolute",
      top: -80,
      left: "50%",
      marginLeft: -100,
      width: 200,
      height: 200,
      borderRadius: 100,
      backgroundColor: c.redGlow,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 16,
      gap: 12,
    },
    backBtn: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: c.cardBg,
      borderWidth: 1,
      borderColor: c.cardBorder,
      alignItems: "center",
      justifyContent: "center",
    },
    headerCenter: { flex: 1, alignItems: "center" },
    vitalBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: c.red + "26",
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: c.red + "4D",
    },
    vitalDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: c.red },
    vitalBadgeText: {
      color: c.red,
      fontSize: 10,
      fontWeight: "800",
      letterSpacing: 1.5,
    },
    timerBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      backgroundColor: c.cardBg,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.cardBorder,
    },
    timerBadgeVital: {
      backgroundColor: c.red + "1A",
      borderColor: c.red + "40",
    },
    timerText: { color: c.textMuted, fontSize: 12, fontWeight: "600" },
    timerTextVital: { color: c.red },
    ineligibleBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: c.amber + "14",
      borderWidth: 1,
      borderColor: c.amber + "40",
      borderRadius: 14,
      padding: 14,
      marginBottom: 20,
    },
    ineligibleTitle: { color: c.amber, fontSize: 14, fontWeight: "700" },
    ineligibleSub: { color: c.textMuted, fontSize: 12, lineHeight: 17 },
    heroBlock: {
      flexDirection: "row",
      alignItems: "center",
      gap: 16,
      marginBottom: 20,
    },
    bloodHero: {
      width: 80,
      height: 80,
      borderRadius: 20,
      backgroundColor: c.red + "1A",
      borderWidth: 2,
      borderColor: c.red + "4D",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    bloodHeroVital: { backgroundColor: c.red, borderColor: c.red },
    bloodHeroText: {
      color: c.red,
      fontSize: 28,
      fontWeight: "900",
      letterSpacing: -1,
    },
    bloodHeroTextVital: { color: "#FFFFFF" },
    rareBadge: {
      position: "absolute",
      bottom: -8,
      backgroundColor: c.amber + "4D",
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
      borderWidth: 1,
      borderColor: c.amber + "80",
    },
    rareText: { color: c.amber, fontSize: 9, fontWeight: "700" },
    heroInfo: { flex: 1, gap: 6 },
    hospitalName: {
      color: c.white,
      fontSize: 18,
      fontWeight: "800",
      letterSpacing: -0.3,
    },
    heroMeta: { flexDirection: "row", alignItems: "center", gap: 5 },
    heroMetaText: { color: c.textMuted, fontSize: 12 },
    metaDot: {
      width: 3,
      height: 3,
      borderRadius: 1.5,
      backgroundColor: c.textSubtle,
      marginHorizontal: 2,
    },
    section: { marginBottom: 16 },
    sectionTitle: {
      color: c.textMuted,
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 1,
      textTransform: "uppercase",
      marginBottom: 10,
    },
    infoCard: {
      backgroundColor: c.cardBg,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: c.cardBorder,
      overflow: "hidden",
    },
    separator: { height: 1, backgroundColor: c.cardBorder, marginLeft: 58 },
    quotaCard: {
      backgroundColor: c.cardBg,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: c.cardBorder,
      padding: 16,
      gap: 12,
    },
    quotaNumbers: { flexDirection: "row", alignItems: "baseline", gap: 4 },
    quotaConfirmed: { color: c.red, fontSize: 32, fontWeight: "800" },
    quotaSeparator: { color: c.textSubtle, fontSize: 24, fontWeight: "300" },
    quotaNeeded: { color: c.white, fontSize: 32, fontWeight: "800" },
    quotaUnit: { color: c.textMuted, fontSize: 14, marginLeft: 6 },
    quotaBarBg: {
      height: 6,
      borderRadius: 3,
      backgroundColor: c.cardBorder,
      overflow: "hidden",
    },
    quotaBarFill: { height: "100%", borderRadius: 3 },
    quotaHint: { color: c.textMuted, fontSize: 12 },
    confirmBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: c.red,
      borderRadius: 16,
      paddingVertical: 14,
      paddingHorizontal: 18,
    },
    confirmBtnVital: {
      shadowColor: c.red,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.35,
      shadowRadius: 12,
      elevation: 8,
    },
    confirmBtnDisabled: { opacity: 0.45 },
    confirmIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: "rgba(255,255,255,0.15)",
      alignItems: "center",
      justifyContent: "center",
    },
    confirmBtnText: {
      color: "#FFFFFF",
      fontSize: 15,
      fontWeight: "700",
      letterSpacing: 0.2,
    },
    confirmBtnSub: {
      color: "rgba(255,255,255,0.55)",
      fontSize: 11,
      marginTop: 1,
    },
    declineBtn: {
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      backgroundColor: "transparent",
      borderWidth: 1.5,
      borderColor: c.cardBorder,
      borderRadius: 16,
      paddingVertical: 14,
      paddingHorizontal: 12,
      minWidth: 104,
    },
    declineBtnDisabled: { opacity: 0.4 },
    declineBtnText: { color: c.textMuted, fontSize: 14, fontWeight: "600" },
    relayBtn: {
      backgroundColor: c.amber + "1A",
      borderWidth: 1.5,
      borderColor: c.amber + "59",
      shadowColor: c.amber,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 4,
      flex: 1,
    },
    errorText: { color: c.textMuted, fontSize: 16 },
    errorBack: {
      backgroundColor: c.red,
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 12,
    },
    errorBackText: { color: "#FFFFFF", fontWeight: "700" },
  }));

  return { styles };
}
