import { useThemedStyles } from "@/src/theme/useTheme";
import { useBottomTabBarHeight } from "@/src/hooks/useTabBarHeight";

export function useDonorDayDetailStyles() {
  const tabBarHeight = useBottomTabBarHeight();

  const styles = useThemedStyles((c) => ({
    container: { flex: 1, backgroundColor: c.bg },
    safeArea: { flex: 1 },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 12,
      gap: 12,
    },
    backBtn: {
      width: 38,
      height: 38,
      borderRadius: 12,
      backgroundColor: c.cardBg,
      alignItems: "center",
      justifyContent: "center",
    },
    headerTitle: { color: c.white, fontSize: 16, fontWeight: "700", flex: 1 },
    cover: { height: 200, backgroundColor: c.red + "05" },
    coverImage: { width: "100%", height: "100%" },
    coverPlaceholder: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
    },
    scrollContent: { paddingBottom: tabBarHeight + 100 }, // ← TabBar intégrée
    body: { padding: 20, gap: 20 },
    structureRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: c.cardBg,
      borderRadius: 14,
      padding: 14,
      borderWidth: 1,
      borderColor: c.cardBorder,
    },
    structureIcon: {
      width: 42,
      height: 42,
      borderRadius: 12,
      backgroundColor: c.red + "12",
      alignItems: "center",
      justifyContent: "center",
    },
    structureName: { color: c.white, fontSize: 15, fontWeight: "600" },
    structureAddress: { color: c.textMuted, fontSize: 12, marginTop: 2 },
    title: {
      color: c.white,
      fontSize: 24,
      fontWeight: "800",
      letterSpacing: -0.5,
      lineHeight: 30,
    },
    metaGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
    metaCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: c.cardBg,
      borderRadius: 10,
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderWidth: 1,
      borderColor: c.cardBorder,
    },
    metaText: { color: c.textMuted, fontSize: 13, fontWeight: "500" },
    bloodRow: { flexDirection: "row", gap: 6, flexWrap: "wrap" },
    pill: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 8,
      backgroundColor: c.red + "08",
      borderWidth: 1,
      borderColor: c.red + "20",
    },
    pillText: { color: c.red, fontSize: 11, fontWeight: "700" },
    emptyPill: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 8,
      backgroundColor: c.cardBorder + "15",
      borderWidth: 1,
      borderColor: c.cardBorder + "25",
    },
    emptyPillText: { color: c.textMuted, fontSize: 11, fontWeight: "600" },
    statsRow: { flexDirection: "row", gap: 10 },
    statCard: {
      flex: 1,
      backgroundColor: c.cardBg,
      borderRadius: 14,
      padding: 14,
      alignItems: "center",
      gap: 4,
      borderWidth: 1,
      borderColor: c.cardBorder,
    },
    statValue: { fontSize: 20, fontWeight: "800", color: c.white },
    statLabel: { fontSize: 11, color: c.textMuted, fontWeight: "500" },
    eligibilityBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: c.amber + "10",
      borderWidth: 1.5,
      borderColor: c.amber + "35",
      borderRadius: 14,
      padding: 14,
    },
    eligibilityText: {
      color: c.amber,
      fontSize: 13,
      fontWeight: "600",
      flex: 1,
      lineHeight: 18,
    },
    description: { color: c.textMuted, fontSize: 14, lineHeight: 22 },
    footer: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 10 + tabBarHeight,
      backgroundColor: c.bg + "EE",
    }, // ← TabBar intégrée
    ctaBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      backgroundColor: c.red,
      borderRadius: 16,
      paddingVertical: 17,
    },
    ctaBtnDisabled: { opacity: 0.5 },
    ctaBtnText: { color: c.white, fontSize: 16, fontWeight: "700" },
    cancelBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: 14,
      borderRadius: 16,
      backgroundColor: c.cardBg,
      borderWidth: 1,
      borderColor: c.red + "40",
    },
    cancelBtnText: { color: c.red, fontSize: 14, fontWeight: "600" },
    errorContainer: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      padding: 20,
    },
    errorTitle: {
      color: c.white,
      fontSize: 18,
      fontWeight: "700",
      marginTop: 16,
      textAlign: "center",
    },
  }));

  return { styles };
}
