import { useThemedStyles } from "@/src/theme/useTheme";

export function useDonorHomeStyles(tabBarHeight: number = 72) {
  const styles = useThemedStyles((c) => ({
    container: { flex: 1, backgroundColor: c.bg },
    listContent: {
      paddingHorizontal: 20,
      paddingBottom: 20 + tabBarHeight,
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 16,
    },
    greeting: { color: c.textMuted, fontSize: 13, fontWeight: "500" },
    headerTitle: {
      color: c.white,
      fontSize: 24,
      fontWeight: "800",
      letterSpacing: -0.5,
    },
    bellBtn: {
      width: 44,
      height: 44,
      borderRadius: 13,
      backgroundColor: c.cardBg,
      borderWidth: 1,
      borderColor: c.cardBorder,
      alignItems: "center",
      justifyContent: "center",
      position: "relative",
    },
    bellBadge: {
      position: "absolute",
      top: -4,
      right: -4,
      minWidth: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: c.red,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: c.bg,
      paddingHorizontal: 3,
    },
    bellBadgeText: { color: c.white, fontSize: 10, fontWeight: "800" },
    availRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginHorizontal: 20,
      marginBottom: 16,
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 14,
      borderWidth: 1,
    },
    availRowOn: {
      backgroundColor: "rgba(29,158,117,0.08)",
      borderColor: "rgba(29,158,117,0.22)",
    },
    availRowOff: { backgroundColor: c.cardBg, borderColor: c.cardBorder },
    availLeft: { flexDirection: "row", alignItems: "center", gap: 10, flex: 1 },
    availDot: { width: 8, height: 8, borderRadius: 4 },
    availDotOn: { backgroundColor: c.success },
    availDotOff: { backgroundColor: c.textSubtle },
    availTitle: { color: c.white, fontSize: 13, fontWeight: "700" },
    availSub: { color: c.textMuted, fontSize: 11, marginTop: 1 },
    ghostBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      marginHorizontal: 20,
      marginBottom: 16,
      backgroundColor: "rgba(220,30,30,0.08)",
      borderWidth: 1.5,
      borderColor: "rgba(220,30,30,0.30)",
      borderRadius: 16,
      paddingVertical: 14,
      paddingHorizontal: 16,
    },
    ghostTextBlock: { flex: 1, gap: 4 },
    ghostTitle: { color: c.red, fontSize: 14, fontWeight: "700" },
    ghostSub: { color: c.textMuted, fontSize: 12, lineHeight: 16 },
    ghostCancelBtn: {
      backgroundColor: c.red,
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 10,
      flexShrink: 0,
    },
    ghostCancelText: { color: c.white, fontSize: 12, fontWeight: "700" },
    restPeriodBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      backgroundColor: c.success + "14",
      borderWidth: 1,
      borderColor: c.success + "30",
      borderRadius: 14,
      padding: 14,
      marginHorizontal: 20,
      marginTop: 10,
    },
    restPeriodTitle: {
      color: c.white,
      fontSize: 13,
      fontWeight: "700",
    },
    restPeriodSub: {
      color: c.textMuted,
      fontSize: 12,
    },
    filtersRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 20,
      marginBottom: 14,
      gap: 8,
    },
    filterPill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      paddingVertical: 7,
      paddingHorizontal: 14,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: c.cardBorder,
      backgroundColor: c.cardBg,
    },
    filterPillActive: {
      backgroundColor: "rgba(220,30,30,0.12)",
      borderColor: "rgba(220,30,30,0.35)",
    },
    filterPillVital: {
      backgroundColor: "rgba(220,30,30,0.15)",
      borderColor: "rgba(220,30,30,0.40)",
    },
    filterDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: c.textSubtle,
    },
    filterDotActive: { backgroundColor: c.red },
    filterText: { color: c.textMuted, fontSize: 12, fontWeight: "600" },
    filterTextActive: { color: c.white },
    filterTextVital: { color: c.red },
    filterCount: { marginLeft: "auto" },
    filterCountText: { color: c.textSubtle, fontSize: 11 },
  }));

  return { styles };
}
