import { useThemedStyles } from "@/src/theme/useTheme";
import { useBottomTabBarHeight } from "../hooks/useTabBarHeight";

export function useProfileStyles() {
  const tabBarHeight = useBottomTabBarHeight();

  const styles = useThemedStyles((c) => ({
    container: { flex: 1, backgroundColor: c.bg },
    scrollContent: {
      paddingHorizontal: 20,
      paddingBottom: 16 + tabBarHeight,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingTop: 8,
      paddingBottom: 22,
    },
    headerTitle: {
      color: c.white,
      fontSize: 27,
      fontWeight: "900",
      letterSpacing: -0.5,
    },
    editBtn: {
      width: 38,
      height: 38,
      borderRadius: 12,
      backgroundColor: c.cardBg,
      borderWidth: 0.5,
      borderColor: c.cardBorder,
      alignItems: "center",
      justifyContent: "center",
    },
    heroCard: {
      backgroundColor: c.cardBg,
      borderRadius: 22,
      borderWidth: 0.5,
      borderColor: c.cardBorder,
      padding: 18,
      marginBottom: 20,
      gap: 14,
      overflow: "hidden",
    },
    avatarWrap: { position: "relative", flexShrink: 0 },
    avatarRing: {
      width: 72,
      height: 72,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1.5,
      borderColor: c.cardBorder,
    },
    avatarImage: { width: 68, height: 68, borderRadius: 18 },
    avatarEmoji: { fontSize: 30 },
    heroTop: { flexDirection: "row", alignItems: "center", gap: 14 },
    heroInfo: { flex: 1, gap: 5 },
    userName: {
      color: c.white,
      fontSize: 20,
      fontWeight: "800",
      letterSpacing: -0.3,
    },
    userPhone: { color: c.textMuted, fontSize: 12, fontWeight: "500" },
    pillsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
      marginTop: 3,
      flexWrap: "wrap",
    },
    pill: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      paddingHorizontal: 9,
      paddingVertical: 4,
      borderRadius: 8,
      borderWidth: 0.5,
    },
    pillBlood: {
      backgroundColor: "rgba(220,30,30,0.13)",
      borderColor: "rgba(220,30,30,0.30)",
    },
    pillEmpty: { backgroundColor: c.cardBorder, borderColor: c.cardBorder },
    pillText: { fontSize: 11, fontWeight: "700" },
    pillTextBlood: { color: c.red },
    pillEmoji: { fontSize: 11 },
    statsRow: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: c.inputBg,
      borderRadius: 13,
      borderWidth: 0.5,
      borderColor: c.cardBorder,
      paddingVertical: 11,
    },
    statSep: { width: 0.5, height: 26, backgroundColor: c.cardBorder },
    eligRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 11,
      padding: 12,
      borderRadius: 13,
    },
    eligRowGreen: {
      backgroundColor: "rgba(29,158,117,0.07)",
      borderWidth: 0.5,
      borderColor: "rgba(29,158,117,0.20)",
    },
    eligRowAmber: {
      backgroundColor: "rgba(250,199,117,0.06)",
      borderWidth: 0.5,
      borderColor: "rgba(250,199,117,0.18)",
    },
    eligDot: { width: 7, height: 7, borderRadius: 4, flexShrink: 0 },
    eligTitle: { fontSize: 13, fontWeight: "700", marginBottom: 1 },
    eligSub: { color: c.textMuted, fontSize: 11, lineHeight: 15 },
    eligIcon: {
      width: 26,
      height: 26,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    section: { marginBottom: 18 },
    sectionTitle: {
      color: c.textSubtle,
      fontSize: 10,
      fontWeight: "700",
      letterSpacing: 1.5,
      marginBottom: 9,
    },
    card: {
      backgroundColor: c.cardBg,
      borderRadius: 16,
      borderWidth: 0.5,
      borderColor: c.cardBorder,
      overflow: "hidden",
    },
    rowHint: { color: c.textMuted, fontSize: 11, marginTop: 1 },
    sep: { height: 0.5, backgroundColor: c.cardBorder, marginLeft: 58 },
    availIconWrap: {
      width: 34,
      height: 34,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    availRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 11,
      padding: 13,
      minHeight: 50,
      paddingRight: 8,
    },
    actions: { marginTop: 6, gap: 10, alignItems: "center", paddingBottom: 20 },
    logoutBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      width: "100%",
      paddingVertical: 14,
      borderRadius: 15,
      borderWidth: 0.5,
      borderColor: "rgba(220,30,30,0.30)",
      backgroundColor: "rgba(220,30,30,0.05)",
    },
    logoutText: { color: c.red, fontSize: 15, fontWeight: "700" },
    deleteText: { color: c.textSubtle, fontSize: 13, fontWeight: "500" },
    versionText: {
      color: c.textSubtle,
      fontSize: 10,
      opacity: 0.5,
      marginTop: 4,
    },
  }));

  return { styles };
}
