import { useThemedStyles } from "@/src/theme/useTheme";
import { useBottomTabBarHeight } from "@/src/hooks/useTabBarHeight";

export function useQrCodeStyles() {
  const tabBarHeight = useBottomTabBarHeight();

  const styles = useThemedStyles((c) => ({
    container: { flex: 1, backgroundColor: c.bg },
    safeArea: { flex: 1 },
    scrollContent: { flexGrow: 1, paddingBottom: 20 + tabBarHeight },
    centered: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      gap: 16,
      paddingHorizontal: 40,
    },
    haloTop: {
      position: "absolute",
      top: -60,
      right: -40,
      width: 200,
      height: 200,
      borderRadius: 100,
      backgroundColor: c.redGlow,
    },
    haloBottom: {
      position: "absolute",
      bottom: 80,
      left: -60,
      width: 160,
      height: 160,
      borderRadius: 80,
      backgroundColor: c.haloLight,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 12,
    },
    headerBtn: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: c.cardBg,
      borderWidth: 1,
      borderColor: c.cardBorder,
      alignItems: "center",
      justifyContent: "center",
    },
    headerCenter: { flex: 1, alignItems: "center" },
    successBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: "rgba(29,158,117,0.12)",
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: "rgba(29,158,117,0.25)",
    },
    successDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: c.success,
    },
    successBadgeText: { color: c.success, fontSize: 11, fontWeight: "700" },
    titleBlock: {
      paddingHorizontal: 24,
      paddingBottom: 16,
      alignItems: "center",
      gap: 6,
    },
    title: {
      color: c.white,
      fontSize: 24,
      fontWeight: "800",
      letterSpacing: -0.5,
      textAlign: "center",
    },
    subtitle: {
      color: c.textMuted,
      fontSize: 14,
      textAlign: "center",
      lineHeight: 21,
    },
    qrCardWrapper: { paddingHorizontal: 24, marginBottom: 20 },
    qrCard: {
      backgroundColor: "#FFFFFF",
      borderRadius: 24,
      overflow: "hidden",
      shadowColor: c.red,
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.18,
      shadowRadius: 28,
      elevation: 16,
    },
    qrCardHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 14,
    },
    qrLogoRow: { flexDirection: "row", alignItems: "center", gap: 7 },
    qrLogoIcon: {
      width: 26,
      height: 26,
      borderRadius: 7,
      backgroundColor: c.red,
      alignItems: "center",
      justifyContent: "center",
    },
    qrLogoText: {
      color: "#1A1A1A",
      fontSize: 15,
      fontWeight: "800",
      letterSpacing: -0.3,
    },
    qrCardLabel: {
      color: "rgba(0,0,0,0.35)",
      fontSize: 11,
      fontWeight: "600",
      letterSpacing: 0.5,
    },
    dottedLine: {
      height: 1,
      marginHorizontal: 20,
      borderStyle: "dashed",
      borderWidth: 1,
      borderColor: "rgba(0,0,0,0.10)",
    },
    qrWrapper: {
      alignItems: "center",
      paddingVertical: 24,
      backgroundColor: "#FFFFFF",
    },
    codeBlock: {
      alignItems: "center",
      paddingVertical: 16,
      paddingHorizontal: 20,
      gap: 4,
    },
    codeLabel: {
      color: "rgba(0,0,0,0.35)",
      fontSize: 9,
      fontWeight: "700",
      letterSpacing: 2,
    },
    codeValue: {
      color: c.red,
      fontSize: 20,
      fontWeight: "900",
      letterSpacing: 2.5,
      textAlign: "center",
    },
    bottomBlock: {
      paddingHorizontal: 24,
      gap: 14,
      marginTop: "auto",
      justifyContent: "flex-end",
    },
    instructionRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: 12,
      backgroundColor: "rgba(29,158,117,0.07)",
      borderRadius: 14,
      borderWidth: 1,
      borderColor: "rgba(29,158,117,0.18)",
      padding: 14,
    },
    instructionIcon: {
      width: 32,
      height: 32,
      borderRadius: 9,
      backgroundColor: "rgba(29,158,117,0.12)",
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    instructionText: {
      flex: 1,
      color: "rgba(29,158,117,0.85)",
      fontSize: 13,
      lineHeight: 20,
    },
    shareBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: 15,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: c.cardBorder,
      backgroundColor: c.cardBg,
    },
    shareBtnText: { color: c.white, fontSize: 15, fontWeight: "600" },
    cancelBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: 14,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: c.amber + "40",
      backgroundColor: c.amber + "10",
    },
    cancelBtnExpired: { borderColor: c.cardBorder, backgroundColor: c.cardBg },
    cancelBtnText: { color: c.amber, fontSize: 14, fontWeight: "600" },
    cancelBtnTextExpired: { color: c.textMuted },
    securityRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
    securityText: {
      color: c.textSubtle,
      fontSize: 11,
      textAlign: "center",
      lineHeight: 16,
    },
    errorIconWrap: {
      width: 72,
      height: 72,
      borderRadius: 20,
      backgroundColor: "rgba(220,30,30,0.10)",
      alignItems: "center",
      justifyContent: "center",
    },
    errorTitle: {
      color: c.white,
      fontSize: 18,
      fontWeight: "700",
      textAlign: "center",
    },
    errorSub: {
      color: c.textMuted,
      fontSize: 14,
      textAlign: "center",
      lineHeight: 21,
    },
    errorBtn: {
      backgroundColor: c.red,
      paddingHorizontal: 28,
      paddingVertical: 13,
      borderRadius: 14,
      marginTop: 8,
    },
    errorBtnText: { color: c.white, fontWeight: "700", fontSize: 15 },
  }));

  return { styles };
}
