import { useThemedStyles } from "@/src/theme/useTheme";

export const useOtpVerifyStyles = () => {
  return useThemedStyles((c) => ({
    container: { flex: 1, backgroundColor: c.bg },
    safeArea: { flex: 1, paddingHorizontal: 24 },
    haloCenter: {
      position: "absolute",
      top: -80,
      left: "50%",
      marginLeft: -120,
      width: 240,
      height: 240,
      borderRadius: 120,
      backgroundColor: c.redGlow,
    },
    backBtn: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: c.cardBg,
      borderWidth: 1,
      borderColor: c.cardBorder,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 8,
      marginBottom: 32,
    },
    body: {
      flex: 1,
      alignItems: "center",
    },
    iconWrap: {
      position: "relative",
      marginBottom: 24,
    },
    iconOuter: {
      width: 80,
      height: 80,
      borderRadius: 24,
      backgroundColor: "rgba(220,30,30,0.10)",
      borderWidth: 1,
      borderColor: "rgba(220,30,30,0.22)",
      alignItems: "center",
      justifyContent: "center",
    },
    iconInner: {
      width: 56,
      height: 56,
      borderRadius: 16,
      backgroundColor: "rgba(220,30,30,0.14)",
      alignItems: "center",
      justifyContent: "center",
    },
    iconBadge: {
      position: "absolute",
      bottom: -4,
      right: -4,
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: c.success,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: c.bg,
    },
    textBlock: {
      alignItems: "center",
      gap: 8,
      marginBottom: 32,
    },
    title: {
      color: c.white,
      fontSize: 26,
      fontWeight: "800",
      letterSpacing: -0.5,
    },
    subtitle: {
      color: c.textMuted,
      fontSize: 14,
      textAlign: "center",
      lineHeight: 22,
    },
    emailHighlight: {
      color: c.white,
      fontWeight: "600",
    },
    errorCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: "rgba(239,68,68,0.09)",
      borderRadius: 12,
      borderWidth: 1,
      borderColor: "rgba(239,68,68,0.20)",
      paddingHorizontal: 14,
      paddingVertical: 10,
      marginBottom: 16,
      alignSelf: "stretch",
    },
    errorText: {
      color: "#EF4444",
      fontSize: 13,
      flex: 1,
      lineHeight: 18,
    },
    timerBlock: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    timerCircle: {
      width: 28,
      height: 28,
      borderRadius: 14,
      borderWidth: 1.5,
      alignItems: "center",
      justifyContent: "center",
    },
    timerText: {
      fontSize: 22,
      fontWeight: "800",
      letterSpacing: 1.5,
    },
    timerLabel: {
      color: c.textMuted,
      fontSize: 13,
    },
    expiredCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      backgroundColor: "rgba(239,68,68,0.09)",
      borderRadius: 12,
      borderWidth: 1,
      borderColor: "rgba(239,68,68,0.20)",
      paddingHorizontal: 14,
      paddingVertical: 10,
    },
    expiredText: {
      color: "#EF4444",
      fontSize: 13,
      fontWeight: "500",
    },
    footer: {
      paddingBottom: 10,
      gap: 14,
    },
    ctaBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      backgroundColor: c.red,
      borderRadius: 16,
      paddingVertical: 17,
    },
    ctaBtnDisabled: { opacity: 0.45 },
    ctaBtnText: {
      color: c.white,
      fontSize: 16,
      fontWeight: "700",
      letterSpacing: 0.2,
    },
    ctaBtnIcon: {
      width: 28,
      height: 28,
      borderRadius: 8,
      backgroundColor: "rgba(255,255,255,0.18)",
      alignItems: "center",
      justifyContent: "center",
    },
    resendRow: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 4,
    },
    resendText: {
      color: c.textMuted,
      fontSize: 14,
    },
    resendLink: {
      color: c.red,
      fontSize: 14,
      fontWeight: "700",
    },
    resendCountdown: {
      color: c.textSubtle,
      fontSize: 13,
      fontWeight: "500",
    },
    securityInfo: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
    },
    securityText: {
      color: c.textSubtle,
      fontSize: 11,
      letterSpacing: 0.3,
    },
  }));
};
